services:
  postgres:
    image: postgres:16
    container_name: trading-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_engine
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7
    container_name: trading-redis
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: amitumbare/trading-backend
    container_name: trading-backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trading_engine
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: amitumbare/trading-frontend
    container_name: trading-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data: